### ISSUE TITLE
Add a sign_up mutation to the backend

### ISSUE THREAD

**Issue by hjarrell** [ufosc/AskAGator#119]
Add a signup mutation to the backed for a new user to be created. This should take a name, email, password, password_confirmation, and either return success or failure.

**Comment by ngynkvn** [comment]
Hi, new to elixir but I love the project you're doing, was wondering if I could try implementing this feature / if you're accepting contributions at this time

**Comment by hjarrell** [comment]
Yeah that'd be great! If you have questions or want to go over anything you can reach me in the discord: discord.gg/Gsxej6u @hjarrell.
